### ISSUE TITLE
(cons [1 2 3] 4) throws an error

### ISSUE THREAD

**Issue by sea-witch** [anan44/it-starts-with-clojure#17]
Hi there! I'm new to Clojure, so forgive me if I'm mistaken, but it seems that the example on line 121 of ["1-adding-to-data-structures.md"](https://github.com/anan44/it-starts-with-clojure/edit/master/materials/4-state-in-clojure/1-adding-to-data-structures.md) throws an error.

```
(cons [1 2 3] 4)
```

Results in:
```
Execution error (IllegalArgumentException) at clojure-todo.core/eval7648 (form-init12489491878621654268.clj:1).
Don't know how to create ISeq from: java.lang.Long
class java.lang.IllegalArgumentException
```
It seems this is because we're trying to `cons` something onto a `Long`, namely `4`? Maybe I'm missing the intent of this example? Either way, it would be good to clarify what's going on here.

(Thank you for this wonderful guide!)

**Comment by anan44** [comment]
Hi saoirse-zee,

Thanks for pointing this out. This is a clear bug in the guide, and this line should never have been there in the first place. I have now removed this line. 

If you find more issues please let me know. I will gladly fix them.
